import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../models/duty_proof_model.dart';
import '../../models/notification_model.dart';
import 'dart:convert';

class DutyProofReviewScreen extends StatefulWidget {
  const DutyProofReviewScreen({super.key});

  @override
  State<DutyProofReviewScreen> createState() => _DutyProofReviewScreenState();
}

class _DutyProofReviewScreenState extends State<DutyProofReviewScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  Stream<List<DutyProofModel>> _proofsStream(String? status) {
    Query query = FirebaseFirestore.instance.collection('duty_proofs');
    if (status != null) {
      query = query.where('status', isEqualTo: status);
    }
    return query
        .orderBy('submittedAt', descending: true)
        .snapshots()
        .map(
          (snap) =>
              snap.docs
                  .map(
                    (d) => DutyProofModel.fromMap(
                      d.data() as Map<String, dynamic>,
                      d.id,
                    ),
                  )
                  .toList(),
        );
  }

  Future<void> _updateStatus(String proofId, DutyProofStatus status) async {
    // 1. Get the proof data to know the user
    final proofDoc = await FirebaseFirestore.instance.collection('duty_proofs').doc(proofId).get();
    if (!proofDoc.exists) return;
    final proofData = proofDoc.data() as Map<String, dynamic>;
    final String userId = proofData['submittedBy'] ?? '';
    final String location = proofData['location'] ?? 'Duty Area';

    // 2. Update the status
    await FirebaseFirestore.instance
        .collection('duty_proofs')
        .doc(proofId)
        .update({'status': status.name});
    
    // 3. Create a notification for the resident
    if (userId.isNotEmpty) {
      final notification = NotificationModel(
        id: '', // Will be generated by Firestore
        userId: userId,
        title: status == DutyProofStatus.approved ? 'Duty Approved ✓' : 'Duty Rejected ✗',
        message: status == DutyProofStatus.approved 
          ? 'Your report for $location has been approved. Good job!' 
          : 'Your report for $location was rejected. Please re-submit with better proof.',
        createdAt: DateTime.now(),
        type: status == DutyProofStatus.approved ? NotificationType.approval : NotificationType.rejection,
        isRead: false,
      );

      await FirebaseFirestore.instance.collection('notifications').add(notification.toMap());
    }

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            status == DutyProofStatus.approved
                ? 'Proof Approved ✓'
                : 'Proof Rejected',
          ),
          backgroundColor:
              status == DutyProofStatus.approved ? Colors.green : Colors.red,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF4F6F9),
      appBar: AppBar(
        title: const Text('Proof Review'),
        backgroundColor: const Color(0xFF2196F3),
        foregroundColor: Colors.white,
        elevation: 0,
        bottom: TabBar(
          controller: _tabController,
          indicatorColor: Colors.white,
          labelColor: Colors.white,
          unselectedLabelColor: Colors.white60,
          tabs: const [
            Tab(text: 'Pending'),
            Tab(text: 'Approved'),
            Tab(text: 'Rejected'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _buildProofList('pending', showActions: true),
          _buildProofList('approved', showActions: false),
          _buildProofList('rejected', showActions: false),
        ],
      ),
    );
  }

  Widget _buildProofList(String status, {required bool showActions}) {
    return StreamBuilder<List<DutyProofModel>>(
      stream: _proofsStream(status),
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          return Center(
            child: Padding(
              padding: const EdgeInsets.all(24),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Icon(Icons.error_outline, color: Colors.red, size: 48),
                  const SizedBox(height: 16),
                  Text("Error: ${snapshot.error}", textAlign: TextAlign.center),
                  const SizedBox(height: 16),
                  ElevatedButton(
                    onPressed: () => setState(() {}),
                    child: const Text("Retry"),
                  )
                ],
              ),
            ),
          );
        }
        if (!snapshot.hasData) {
          return const Center(child: CircularProgressIndicator());
        }

        final proofs = snapshot.data!;
        if (proofs.isEmpty) {
          return Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(
                  Icons.task_alt_outlined,
                  size: 56,
                  color: Colors.grey.shade300,
                ),
                const SizedBox(height: 12),
                Text(
                  'No $status submissions',
                  style: TextStyle(color: Colors.grey.shade400, fontSize: 14),
                ),
              ],
            ),
          );
        }

        return ListView.builder(
          padding: const EdgeInsets.all(16),
          itemCount: proofs.length,
          itemBuilder:
              (context, index) =>
                  _buildProofCard(proofs[index], showActions: showActions),
        );
      },
    );
  }

  Widget _buildProofCard(DutyProofModel proof, {required bool showActions}) {
    final statusColor =
        proof.status == DutyProofStatus.approved
            ? Colors.green
            : proof.status == DutyProofStatus.rejected
            ? Colors.red
            : Colors.orange;

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(18),
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.08),
            blurRadius: 10,
            offset: const Offset(0, 3),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: BoxDecoration(
              color: statusColor.withOpacity(0.08),
              borderRadius: const BorderRadius.vertical(
                top: Radius.circular(18),
              ),
            ),
            child: Row(
              children: [
                CircleAvatar(
                  radius: 18,
                  backgroundColor: statusColor.withOpacity(0.2),
                  child: Text(
                    proof.submittedByName.isNotEmpty
                        ? proof.submittedByName[0].toUpperCase()
                        : '?',
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      color: statusColor,
                    ),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        proof.submittedByName,
                        style: const TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                      Text(
                        _formatDate(proof.submittedAt),
                        style: TextStyle(
                          fontSize: 12,
                          color: Colors.grey.shade500,
                        ),
                      ),
                    ],
                  ),
                ),
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 10,
                    vertical: 4,
                  ),
                  decoration: BoxDecoration(
                    color: statusColor.withOpacity(0.15),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Text(
                    proof.status.name.toUpperCase(),
                    style: TextStyle(
                      fontSize: 11,
                      color: statusColor,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
          ),

          // Description
          Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                if (proof.zone != null || proof.location != null) ...[
                  Row(
                    children: [
                      const Icon(Icons.location_on_outlined, size: 14, color: Color(0xFF2196F3)),
                      const SizedBox(width: 6),
                      Text(
                        '${proof.zone ?? ""} • ${proof.location ?? ""}',
                        style: const TextStyle(
                          fontSize: 13,
                          fontWeight: FontWeight.bold,
                          color: Color(0xFF2196F3),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                ],
                if (proof.imageUrl != null) ...[
                  ClipRRect(
                    borderRadius: BorderRadius.circular(12),
                    child: proof.imageUrl!.startsWith('data:image')
                        // Legacy base64 support
                        ? Image.memory(
                            base64Decode(proof.imageUrl!.split(',').last),
                            height: 180,
                            width: double.infinity,
                            fit: BoxFit.cover,
                            errorBuilder: (ctx, err, stack) => Container(
                              height: 100,
                              color: Colors.grey.shade100,
                              child: const Center(child: Icon(Icons.image_not_supported_outlined, color: Colors.grey)),
                            ),
                          )
                        // Cloudinary / Firebase Storage URL
                        : Image.network(
                            proof.imageUrl!,
                            height: 180,
                            width: double.infinity,
                            fit: BoxFit.cover,
                            loadingBuilder: (ctx, child, progress) {
                              if (progress == null) return child;
                              return SizedBox(
                                height: 180,
                                child: Center(
                                  child: CircularProgressIndicator(
                                    value: progress.expectedTotalBytes != null
                                        ? progress.cumulativeBytesLoaded / progress.expectedTotalBytes!
                                        : null,
                                  ),
                                ),
                              );
                            },
                            errorBuilder: (ctx, err, stack) => Container(
                              height: 100,
                              color: Colors.grey.shade100,
                              child: const Center(child: Icon(Icons.image_not_supported_outlined, color: Colors.grey)),
                            ),
                          ),
                  ),
                  const SizedBox(height: 12),
                ],
                Text(
                  proof.description,
                  style: const TextStyle(
                    fontSize: 14,
                    color: Colors.black87,
                    height: 1.4,
                  ),
                ),
              ],
            ),
          ),

          // Actions (only for pending)
          if (showActions) ...[
            const Divider(height: 1),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
              child: Row(
                children: [
                  Expanded(
                    child: OutlinedButton.icon(
                      onPressed:
                          () =>
                              _updateStatus(proof.id, DutyProofStatus.rejected),
                      icon: const Icon(Icons.close, size: 16),
                      label: const Text('Reject'),
                      style: OutlinedButton.styleFrom(
                        foregroundColor: Colors.red,
                        side: const BorderSide(color: Colors.red),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: ElevatedButton.icon(
                      onPressed:
                          () =>
                              _updateStatus(proof.id, DutyProofStatus.approved),
                      icon: const Icon(Icons.check, size: 16),
                      label: const Text('Approve'),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: Colors.green,
                        foregroundColor: Colors.white,
                        elevation: 0,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }

  String _formatDate(DateTime dt) {
    const months = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ];
    final hour = dt.hour > 12 ? dt.hour - 12 : (dt.hour == 0 ? 12 : dt.hour);
    final min = dt.minute.toString().padLeft(2, '0');
    final period = dt.hour >= 12 ? 'PM' : 'AM';
    return '${months[dt.month - 1]} ${dt.day}, ${dt.year} • $hour:$min $period';
  }
}
