// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ENXbGb8pa1AeuUkxig-o85C3H9DLrHc',
    appId: '1:1090176044986:web:eda869f6dd1c7c18001783',
    messagingSenderId: '1090176044986',
    projectId: 'dormapp-b9bde',
    authDomain: 'dormapp-b9bde.firebaseapp.com',
    storageBucket: 'dormapp-b9bde.firebasestorage.app',
    measurementId: 'G-36YMHS2TCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3rQhn24k0oWRevLRS8PSLZ1hrrVnyuo4',
    appId: '1:1090176044986:android:98c18c147d06fe6f001783',
    messagingSenderId: '1090176044986',
    projectId: 'dormapp-b9bde',
    storageBucket: 'dormapp-b9bde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCztpeOmCes-_iFEsq0BkNlhHF2XAIWjzQ',
    appId: '1:1090176044986:ios:ce48d08c6359c495001783',
    messagingSenderId: '1090176044986',
    projectId: 'dormapp-b9bde',
    storageBucket: 'dormapp-b9bde.firebasestorage.app',
    iosBundleId: 'com.example.dormApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCztpeOmCes-_iFEsq0BkNlhHF2XAIWjzQ',
    appId: '1:1090176044986:ios:ce48d08c6359c495001783',
    messagingSenderId: '1090176044986',
    projectId: 'dormapp-b9bde',
    storageBucket: 'dormapp-b9bde.firebasestorage.app',
    iosBundleId: 'com.example.dormApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ENXbGb8pa1AeuUkxig-o85C3H9DLrHc',
    appId: '1:1090176044986:web:5e17f8ecd48a18ba001783',
    messagingSenderId: '1090176044986',
    projectId: 'dormapp-b9bde',
    authDomain: 'dormapp-b9bde.firebaseapp.com',
    storageBucket: 'dormapp-b9bde.firebasestorage.app',
    measurementId: 'G-D271SZMFWJ',
  );
}
